### ISSUE TITLE
Empty rows

### ISSUE THREAD

**Issue by cpavloud** [emo-bon/observatory-vb-crate#3]
It is not practical and good data management to have empty rows https://github.com/emo-bon/observatory-vb-crate/blob/main/logsheets/transformed/water_measured.csv

@melinalou

**Comment by melinalou** [comment]
do not have the permission to delete them

**Comment by cpavloud** [comment]
@melanthia can you do it?

**Comment by cpavloud** [comment]
I think this is not relevant anymore.
